# Loading Models for 3 Class Model

In [ ]:
import tensorflow as tf
from tensorflow import keras
from transformers import AutoTokenizer, TFBertModel 

In [ ]:
new_model = tf.keras.models.load_model('/content/drive/MyDrive/My Folders/NLP_Research/bert_base_cased_basic_maslow_3_classifier.h5',custom_objects={'TFBertModel': TFBertModel})

In [ ]:
new_model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_ids (InputLayer)         [(None, None)]       0           []                               
                                                                                                  
 attention_mask (InputLayer)    [(None, None)]       0           []                               
                                                                                                  
 tf_bert_model_3 (TFBertModel)  TFBaseModelOutputWi  108310272   ['input_ids[0][0]',              
                                thPoolingAndCrossAt               'attention_mask[0][0]']         
                                tentions(last_hidde                                               
                                n_state=(None, None                                         

In [ ]:
import pandas as pd 
df = pd.read_csv('basic_advanced_reference.csv')
df = df.iloc[0:10][:]
df = df[['sentence','maslow']]
counter = df.copy()
counter['number_of_words'] = counter.sentence.apply(lambda x: len(x.split()))
df = counter.copy()
df['maslow'] = df.maslow.astype('category')
df['maslow'] = df.maslow.cat.codes
tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')
bert = TFBertModel.from_pretrained('bert-base-cased')
data_test = df.copy()

Some layers from the model checkpoint at bert-base-cased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [ ]:
x_test = tokenizer(
    text = data_test.sentence.tolist(),
    add_special_tokens = True,
    max_length = None,
    truncation = True,
    padding = True, 
    return_tensors = 'tf',
    return_token_type_ids = False,
    return_attention_mask = True, 
    verbose = True
)
x_test

{'input_ids': <tf.Tensor: shape=(10, 52), dtype=int32, numpy=
array([[  101,  9350,  1309, 10741,  4077,   119,  9350,  2795,  1146,
         1114,  1123,  6508,  1105,  1245, 15941,   119,  1153,  1355,
         1313,  1105,  1793,  5464,  4077,   119,   102,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0],
       [  101,  1109,  1266,  3416,   170, 12916,  1104,   175,  3377,
          119,  1109,  1488,  8756,  1172,  1304,  2698,   119,  1109,
         1797,  1400,  6340,   119,  4708,  1500,  1172,  1106,  1712,
         1122,  1205,   119,   102,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0],
       [  101,  7312,  5005,  1408,  1280,  1106,  2842,  1278,   119,
         1153,  1450,  1131,  1458,  1106

In [ ]:
predicted_raw = new_model.predict({'input_ids': x_test['input_ids'], 'attention_mask': x_test['attention_mask']}) 

1/1 [==============================] - 3s 3s/step


In [ ]:
import numpy as np 
y_predicted = np.argmax(predicted_raw, axis = 1)

In [ ]:
y_predicted

array([1, 1, 0, 0, 2, 2, 2, 0, 1, 2])